from snakemake.utils import min_version

min_version('8.11')


configfile: 'config/params.json'


module widevariant:
    snakefile: github('fm-key-lab/widevariant_module', path='workflow/Snakefile', tag='0.0.1-alpha')
    config: config


rule all:
    input:
        expand(
            'resources/raw_{info}.csv',
            info=['seq', 'sample']
        )
    localrule: True
    default_target: True


rule:
    output:
        'resources/raw_{info}.xlsx'
    params:
        url=lambda wildcards: config[wildcards.info + '_info_url']
    resources:
        slurm_partition='datatransfer'
    localrule: True
    shell:
        'wget -nc -O {output} {params.url}'


rule:
    input:
        'resources/raw_{info}.xlsx'
    output:
        'results/raw_{info}.csv'
    shell:
        'mv {input} {output}'


onstart:
    shell('rm -f logs/*')
    shell('rm -f .nextflow.log*')


onsuccess:
    shell(f'mkdir -p "/r/t/thosi/{config['run_id']}"')
    shell(f'rsync -au --progress --exclude "work" results "/r/t/thosi/{config['run_id']}/"')