import os

from snakemake.utils import min_version

min_version('8.11')


configfile: os.environ["GROUP_HOME"] + '/config/public_data.json'
configfile: 'config/my_data.json'
configfile: 'config/params.json'


module widevariant:
    snakefile: github('fm-key-lab/widevariant_module', path='workflow/Snakefile', tag='0.0.3-alpha')
    config: config


include: 'rules/samplesheet.smk'
include: 'rules/mapping.smk'
include: 'rules/prepare_results.smk'


rule all:
    input:
        'results/samplesheet.done',
        'results/results.duckdb'
    localrule: True
    default_target: True


onstart:
    shell('find logs -type f ! -path "logs/notebooks/*" -delete')
    shell('rm -f .nextflow.log*')


onsuccess:
    shell(f'mkdir -p "/r/t/thosi/{config['run_id']}"')
    shell(f'rsync -au --progress config "/r/t/thosi/{config['run_id']}/"')
    shell(f'rsync -au --progress --exclude "work" --exclude "results/*/work" results "/r/t/thosi/{config['run_id']}/"')